apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: adwera/go_k8s:v14
        env:
          - name: TOKEN_KEY
            valueFrom:
              secretKeyRef:
                key: TOKEN_KEY
                name: auth-secret
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                key: DB_URL
                name: auth-secret
          - name: MIGRATION_URL
            valueFrom:
              configMapKeyRef:
                key: MIGRATION_URL
                name: app-config
          - name: SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: SERVER_ADDRESS
                name: app-config
          - name: REDIS_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: REDIS_ADDRESS
                name: redis-def-config
          - name: REDIS_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: REDIS_PASSWORD
                name: redis-def-config
        resources:
          limits:
            memory: "512Mi"
            cpu: "800m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: go-backend
spec:
  selector:
    app: go-backend
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
